version: "3"

networks:
  net:
    name: doi-publishing

services:
  api:
    container_name: doi_publishing
    image: "${INTERNAL_REG}/doi-publishing-api:${APP_VERSION}-main"
    build:
      context: .
      args:
        - APP_VERSION=${APP_VERSION}
        - PYTHON_IMG_TAG=${PYTHON_IMG_TAG}
        - MAINTAINER_APP=${MAINTAINER_APP}
        - MAINTAINER_DEVOPS=${MAINTAINER_DEVOPS}
        - EXTERNAL_REG=${EXTERNAL_REG}
      target: prod
    env_file:
      - .env
      - secret/db.env
      - secret/fastapi.env
      - secret/smtp.env
    networks:
      - net
    restart: unless-stopped

  proxy:
    container_name: doi_publishing_proxy
    image: "${INTERNAL_REG}/doi-publishing-api/proxy:${NGINX_IMG_TAG}-main"
    build:
      context: ./nginx
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - NGINX_IMG_TAG=${NGINX_IMG_TAG}
        - MAINTAINER_DEVOPS=${MAINTAINER_DEVOPS}
    depends_on:
      - api
    environment:
      - API_HOST=api:8000
      - AUTH_COOKIE_NAME=envidat
    ports:
      - "50010:80"
    networks:
      - net
