version: "3"

volumes:
  doi-api-test-ckan-db:

networks:
  net:
    name: doi-publishing-db-debug
  envidat:
    external: true

services:
  api:
    container_name: doi_publishing
    image: "${INTERNAL_REG}/doi-publishing-api:${APP_VERSION}-main"
    env_file:
      - .env
      - secret/db.env
      - secret/fastapi.env
      - secret/smtp.env
    environment:
      IS_DOCKER: "True"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net
      - envidat
    restart: unless-stopped

  proxy:
    container_name: doi_publishing_proxy
    image: "${INTERNAL_REG}/doi-publishing-api/proxy:${NGINX_IMG_TAG}-main"
    depends_on:
      - api
    environment:
      - APP_HOST=api:8000
      - AUTH_COOKIE_NAME=envidat
    ports:
      - "50010:80"
    networks:
      - net

  db:
    container_name: ckan_db_copy
    image: "registry-gitlab.wsl.ch/envidat/ckan-container/db:15-main"
    environment:
      - POSTGRES_PASSWORD=ai4ncF6GpHokPaNmW25UftzMjM7hrC
      - PGDATA=/var/lib/postgresql/data/db
    env_file:
      - secret/db-copy.env
    volumes:
      - doi-api-test-ckan-db:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    restart: unless-stopped
