version: "3"

networks:
  net:
    name: doi-publishing-debug

services:
  api:
    container_name: doi_publishing
    image: "${INTERNAL_REG}/doi-publishing-api:${APP_VERSION}-debug"
    build:
      context: .
      args:
        - APP_VERSION=${APP_VERSION}
        - PYTHON_IMG_TAG=${PYTHON_IMG_TAG}
        - MAINTAINER_APP=${MAINTAINER_APP}
        - MAINTAINER_DEVOPS=${MAINTAINER_DEVOPS}
        - EXTERNAL_REG=${EXTERNAL_REG}
      target: debug
    volumes:
      - ./app:/opt/app:ro
    extra_hosts:
      - "pgdboapp.wsl.ch:10.30.1.156"
    env_file:
      - .env
      - secret/debug.env
    environment:
      IS_DOCKER: "True"
    networks:
      - net
    restart: unless-stopped

  proxy:
    container_name: doi_publishing_proxy
    image: "${INTERNAL_REG}/doi-publishing-api/proxy:${NGINX_IMG_TAG}-main"
    build:
      context: ./nginx
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - NGINX_IMG_TAG=${NGINX_IMG_TAG}
        - MAINTAINER_DEVOPS=${MAINTAINER_DEVOPS}
    depends_on:
      - api
    environment:
      - API_HOST=api:8000
      - AUTH_COOKIE_NAME=envidat_local
    ports:
      - "9555:80"
    networks:
      - net
