networks:
  net:
    name: doi-publishing-debug

volumes:
  local-ckan-db:

services:
  api:
    container_name: doi_publishing
    image: "${INTERNAL_REG}/doi-publishing-api:${APP_VERSION}-debug"
    build:
      context: .
      args:
        - APP_VERSION=${APP_VERSION}
        - PYTHON_IMG_TAG=${PYTHON_IMG_TAG}
        - EXTERNAL_REG=${EXTERNAL_REG}
      target: debug
    volumes:
      - ./app:/opt/app:ro
    extra_hosts:
      - "pgdboapp.wsl.ch:10.30.1.156"
      - "envidatdocker.wsl.ch:10.30.1.126"
    env_file:
      - .env
    networks:
      - net
    restart: unless-stopped

  proxy:
    container_name: doi_publishing_proxy
    image: "${INTERNAL_REG}/doi-publishing-api/proxy:${NGINX_IMG_TAG}-main"
    build:
      context: ./nginx
      args:
        - EXTERNAL_REG=${EXTERNAL_REG}
        - NGINX_IMG_TAG=${NGINX_IMG_TAG}
    depends_on:
      - api
    environment:
      - APP_HOST=api:8000
      - AUTH_COOKIE_NAME=envidat_local
    ports:
      - "9555:80"
    networks:
      - net
    restart: unless-stopped

  db:
    container_name: ckan_db_copy
    image: "registry-gitlab.wsl.ch/envidat/ckan-container/db:15-main"
    environment:
      - POSTGRES_PASSWORD=ai4ncF6GpHokPaNmW25UftzMjM7hrC
      - PGDATA=/var/lib/postgresql/data/db
    env_file:
      - .env
    volumes:
      - local-ckan-db:/var/lib/postgresql/data
    extra_hosts:
      - "pgdboapp.wsl.ch:10.30.1.156"
    networks:
      - net
    ports:
      - 25433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    restart: unless-stopped
