version: "3"

networks:
  net:

services:
  api:
    container_name: doi_publishing
    image: "${INTERNAL_REG}/doi-publishing-api:${APP_VERSION}-debug"
    build:
      context: .
      args:
        - APP_VERSION=${APP_VERSION}
        - PYTHON_IMG_TAG=${PYTHON_IMG_TAG}
        - MAINTAINER_APP=${MAINTAINER_APP}
        - MAINTAINER_DEVOPS=${MAINTAINER_DEVOPS}
        - EXTERNAL_REG=${EXTERNAL_REG}
      target: debug
    volumes:
      - ./app:/opt/app:ro
    ports:
      - "9555:8000"
    extra_hosts:
      - "pgdboapp.wsl.ch:10.30.1.156"
      - "mail.wsl.ch:10.30.1.224"
    env_file:
      - .env
      - secret/db.env
      - secret/fastapi.env
      - secret/smtp.env
    environment:
      DEBUG: "True"
      IS_DOCKER: "True"
    networks:
      - net
    restart: unless-stopped
